export default function Articles() {
    let articles = [ 
        {
            name:"The lifespan of human cells",
            text: `Human cells have a certain life span - as soon as they divide a certain number of times, the pace of their work slows down and they die. Biologists know that cellular "clocks" are structures at the end of chromosomes known as "telomeres". Each cell division shortens telomeres and leads to a disastrous countdown of the life of the cell and, ultimately, the entire organism.
             In a study published in Nature Structural and Molecular Biology, a team of American scientists reveals how the cell wears out, telomeres shorten and how DNA undergoes significant changes. Probably, it was possible to detect the very factor that people call "aging".
             "Before this study, we knew that telomeres get shorter with each division until the cell dies," explains the head of the study, Associate Professor Jan Karlseder (Jan Karlseder). – However, something must transmit a local signal from the end of the chromosome to the nucleus. In theory, this is a pretty powerful signal that should be noticeable, because it causes the death of the entire cell."
             Each time a cell divides, the protective "caps" at the end of the chromosomes (red and green dots) are slightly shortened. When telomeres wear out, the "packaging" of DNA undergoes significant changes, which are probably a factor in aging.
             Scientists began to look for it by comparing the levels of histone proteins in young cells (less than 30 divisions), mature (75 divisions) and old (85 divisions). Histones play an extremely important role and are almost identical in all organisms. They bind DNA strands into chromosomes and create chromatin (a complex of DNA, RNA and proteins), which contains all the genetic instructions necessary for the functioning of the cell.
             Scientists were surprised to find that aging cells simply produce fewer histones than young cells. Histones are necessary for the entire genome, and therefore any event that destroys the "production line" of this protein affects the stability of the entire genome. At the end of an exhaustive comparison of the number of histones after each division, it turned out that there really is a difference in protein levels.
             The usual histone level indicates a healthy young cell with fully functional chromatin. Aging cells, apparently, experience stress, duplicate chromosomes in preparation for cell division and at the same time have difficulty creating healthy chromatin, which, of course, does not lead to the appearance of full-fledged cells.
             Comparison of histone patterns of cells taken from a person aged 9 and 92 years shows an obvious and huge difference in the number of histones. These key experiments suggest that the phenomenon observed in laboratory cell culture is present in living organisms and is directly related to human aging.
             Diseases associated with aging, such as cancer, are largely associated with DNA damage. However, a new study suggests that aging itself is an infinitely complex process: the progressive reduction of telomeres accelerates the aging of chromosomes and is closely intertwined with the epigenetic factor of histone influence. Epigenetic refers to all changes that are not directly related to the "planned" instructions in the DNA. Simply put, the activity of many genes is influenced from the outside, for example, in winter a vole mouse grows thicker fur and this is due to the concentration of melatonin in the blood – in autumn it increases, and in spring it decreases.
             A series of experiments in which a team of scientists tried to rejuvenate old cells confirmed that the signals emitted by telomere contraction cause epigenetic changes. When researchers exposed old cells to telomerase (an enzyme that repairs and lengthens telomeres), they began to demonstrate histone levels similar to those of young cells.
             However, the secret of immortality is not so simple – telomere elongation allows cells to grow much longer and can create so-called "immortal" cells, but this increases the risk of turning the cell into cancer.
             Until now, scientists have mainly focused on the interaction between telomeres and DNA repair mechanisms. These processes are difficult to control. A new study offers an unexplored field for the search for immortality - epigenetic changes in cells at different ages. Currently, scientists are trying to determine whether histones change during a linear process or whether their abrupt decrease occurs at a certain stage of human life. Perhaps the discovery of the life extension technique is not as long to wait as it seems. Moreover, extensions are not for a "miserable" 10-20 years, which are given by a huge effort of a healthy lifestyle and endless expensive medical procedures, but a significant increase in longevity – at times, and maybe by orders of magnitude.`, 
             flag: false 
        }, 
        {
            name:"Cancer cells lengthen their telomeres", 
            text: `Telomeres protect the ends of chromosomes from destruction, but with each new cell division they are gradually wasted. This is one of the main causes of aging, so scientists are actively looking for ways to make telomeres longer. Now they have described a new mechanism for their growth - it turned out that proteins “stuck” on DNA stimulate telomere elongation. It is used by many cancer cells to divide without restriction and remain "immortal".
            All eukaryotic (that is, nuclear) organisms store their genetic material in the form of free-ended chromosomes, unlike bacteria with their circular genomes. However, each time DNA is copied, a small fragment at its end is lost - this is due to the mechanism of nucleic acid replication.
            If this happened uncontrollably, the chromosome would soon begin to be "spent" on such copying. Fortunately, at the ends of chromosomes there are special sections containing many DNA repeats - telomeres, with which special proteins are associated. Telomeres can be compared to plastic aglets on shoelaces that protect them from unraveling.
            Thus, during successive cell divisions, telomeres are “used up” instead of the main part of the chromosome. When they run out (the so-called Hayflick limit is reached), the cell shows signs of degradation or even dies.
            Therefore, lengthening telomeres is one of the promising ways to slow down the aging of the body. Usually, for this, biologists try to increase the activity of telemorases - special enzymes that can complete the construction of the ends of chromosomes. But a new study published in Nucleic Acid Research details a different mechanism, the so-called alternative lengthening of telomeres (ALT).
            The object of research this time were cancer cells. The fact is that tumor cells are able to bypass problems with the “expenditure” of telomeres, due to which they divide without restrictions. This is due to the disruption of the ATRX protein in them: it performs many functions, including affecting DNA packaging and maintaining genome stability.
            Using fluorescent labels, the authors of the scientific work showed that ATRX binds repetitive DNA sequences - there are many of them in telomeres. The researchers then used CRISPR/Cas9 genomic editing to “turn off” the ATRX gene and find out how this affects telomere length.
            It turned out that the absence of the ATRX protein alone is not enough. An alternative pathway for telomere growth also required strong DNA binding to TOP2A topoisomerase. This enzyme is needed for the nucleic acid to move from the "overstressed", supercoiled state - for this, topoisomerases cut the DNA and immediately splice it back.
            But in fact, it turned out that other proteins that are firmly "sewn" to DNA cause the same effect. Scientists noted that such unusually strong bonds between molecules stimulate various radiation and chemotherapy drugs.
            This information can be useful both in the study of aging and in understanding the mechanisms of cancer development.`, 
            flag: false 
        },
    
        {
            name:"Cancer cells lengthen their telomeres 2", 
            text: `Telomeres protect the ends of chromosomes from destruction, but with each new cell division they are gradually wasted. This is one of the main causes of aging, so scientists are actively looking for ways to make telomeres longer. Now they have described a new mechanism for their growth - it turned out that proteins “stuck” on DNA stimulate telomere elongation. It is used by many cancer cells to divide without restriction and remain "immortal".
            All eukaryotic (that is, nuclear) organisms store their genetic material in the form of free-ended chromosomes, unlike bacteria with their circular genomes. However, each time DNA is copied, a small fragment at its end is lost - this is due to the mechanism of nucleic acid replication.
            If this happened uncontrollably, the chromosome would soon begin to be "spent" on such copying. Fortunately, at the ends of chromosomes there are special sections containing many DNA repeats - telomeres, with which special proteins are associated. Telomeres can be compared to plastic aglets on shoelaces that protect them from unraveling.
            Thus, during successive cell divisions, telomeres are “used up” instead of the main part of the chromosome. When they run out (the so-called Hayflick limit is reached), the cell shows signs of degradation or even dies.
            Therefore, lengthening telomeres is one of the promising ways to slow down the aging of the body. Usually, for this, biologists try to increase the activity of telemorases - special enzymes that can complete the construction of the ends of chromosomes. But a new study published in Nucleic Acid Research details a different mechanism, the so-called alternative lengthening of telomeres (ALT).
            The object of research this time were cancer cells. The fact is that tumor cells are able to bypass problems with the “expenditure” of telomeres, due to which they divide without restrictions. This is due to the disruption of the ATRX protein in them: it performs many functions, including affecting DNA packaging and maintaining genome stability.
            Using fluorescent labels, the authors of the scientific work showed that ATRX binds repetitive DNA sequences - there are many of them in telomeres. The researchers then used CRISPR/Cas9 genomic editing to “turn off” the ATRX gene and find out how this affects telomere length.
            It turned out that the absence of the ATRX protein alone is not enough. An alternative pathway for telomere growth also required strong DNA binding to TOP2A topoisomerase. This enzyme is needed for the nucleic acid to move from the "overstressed", supercoiled state - for this, topoisomerases cut the DNA and immediately splice it back.
            But in fact, it turned out that other proteins that are firmly "sewn" to DNA cause the same effect. Scientists noted that such unusually strong bonds between molecules stimulate various radiation and chemotherapy drugs.
            This information can be useful both in the study of aging and in understanding the mechanisms of cancer development.`, 
            flag: false 
        } 
    ]; 


    return articles
}